### ISSUE TITLE
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)

### ISSUE THREAD

**Issue by dannyeuu** [qwj/python-proxy#57]
I had the problem with `http+ssl` with remote server:
``` python
SSL handshake failed
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f2611d7eeb8>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/home/proxy-server/miniconda3/lib/python3.7/asyncio/sslproto.py", line 625, in _on_handshake_complete
    raise handshake_exc
  File "/home/proxy-server/miniconda3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/home/proxy-server/miniconda3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f2611d7eeb8>
transport: <_SelectorSocketTransport closing fd=10 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/home/proxy-server/miniconda3/lib/python3.7/asyncio/sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/home/proxy-server/miniconda3/lib/python3.7/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/home/proxy-server/miniconda3/lib/python3.7/ssl.py", line 763, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)
[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)
```

Is this common?

**Comment by qwj** [comment]
It is not common.
It seems that the https server doesn't have correct SSL version. The Python SSL library failed to connect.
