### ISSUE TITLE
Use logging unstead direct sys.stdout.write

### ISSUE THREAD

**Issue by CrazyLionHeart** [qwj/python-proxy#63]
Then trying to start service as systemd-unit got error:

```
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]: Using uvloop
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]: Traceback (most recent call last):
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "uvloop/loop.pyx", line 740, in uvloop.loop.Loop._add_reader
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]: KeyError: 0
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]: During handling of the above exception, another exception occurred:
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]: Traceback (most recent call last):
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "/usr/local/bin/pproxy", line 11, in <module>
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:     sys.exit(main())
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "/usr/local/lib/python3.6/dist-packages/pproxy/server.py", line 567, in main
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:     verbose.setup(loop, args)
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "/usr/local/lib/python3.6/dist-packages/pproxy/verbose.py", line 66, in setup
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:     loop.add_reader(sys.stdin, functools.partial(all_stat_other, args.stats))
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "uvloop/loop.pyx", line 2389, in uvloop.loop.Loop.add_reader
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "uvloop/loop.pyx", line 742, in uvloop.loop.Loop._add_reader
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "uvloop/handles/poll.pyx", line 29, in uvloop.loop.UVPoll.new
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]:   File "uvloop/handles/poll.pyx", line 17, in uvloop.loop.UVPoll._init
Dec 23 13:46:06 scw-reverent-shockley pproxy[13890]: PermissionError: [Errno 1] Operation not permitted
```

Problem related systemd, because service cannot open sys.stdout device for write/flush

**Comment by qwj** [comment]
Add " > log_file" to redirect or remove "-v" parameter

**Comment by CrazyLionHeart** [comment]
Just for history:

Add in `Service` section:

```
StandardOutput=journal+console
```

And problem disappear
