### ISSUE TITLE
writer.get_extra_info('peername') returns None

### ISSUE THREAD

**Issue by Jonney** [qwj/python-proxy#92]
Task exception was never retrieved
future: <Task finished coro=<stream_handler() done, defined at /usr/local/lib/python3.7/dist-packages/pproxy/server.py:54> exception=Un
boundLocalError("local variable 'remote_ip' referenced before assignment")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pproxy/server.py", line 60, in stream_handler
    remote_ip, remote_port, *_ = writer.get_extra_info('peername')
TypeError: cannot unpack non-iterable NoneType object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pproxy/server.py", line 92, in stream_handler
    verbose(f'{str(ex) or "Unsupported protocol"} from {remote_ip}')
UnboundLocalError: local variable 'remote_ip' referenced before assignment

**Comment by Jonney** [comment]
#93
